[package]
name = "frontstrike_wagering"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.27.0"
anchor-spl = "0.27.0"

[features]
no-entrypoint = []
default = ["no-entrypoint"]
